BookSharingPortal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from loginapp import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^loginapp/',include('loginapp.urls')),
    url(r'^homepage/',include('homepage.urls')),
    url(r'^user_profile/',include('user_profile.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.conf.urls import url
from homepage import views
from django.conf.urls.static import static
from django.conf import settings
# SET THE NAMESPACE!
app_name = 'homepage'

urlpatterns=[
    url(r'^home/$',views.home,name="home"),
    url(r'^profile/$',views.profile,name="profile"),
    url(r'^addpost/$',views.addpost,name="addpost"),
    url(r'^addpost1/$',views.addpost1,name="addpost1"),
    url(r'^myposts/$',views.myPosts,name="myposts"),
    url(r'^delete/$',views.deletePost,name="delete_post"),
    url(r'^edit_post/(?P<p>.*)/$',views.edit_post,name="edit_post"),
    #url(r'^edit_post_data/$',views.edit_post_data,name="edit_post_data"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginapp/urls.py
from django.conf.urls import url
from loginapp import views
from django.conf.urls.static import static
from django.conf import settings
# SET THE NAMESPACE!
app_name = 'loginapp'

urlpatterns=[
    url(r'^$',views.index,name="index"),
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^user_logout/$',views.user_logout,name='user_logout'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import datetime
from django.conf import settings

item_choice = (
   ('B', 'Book'),
   ('S', 'Stationary'),
   ('O','Others'),
)

class itemInfo(models.Model):
   user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=True,blank=False)
   #user = models.ManyToManyField(settings.AUTH_USER_MODEL,null=True,blank=False)
   item_pic1 = models.ImageField(upload_to='item_pics',blank=False,null=True)
   item_pic2 = models.ImageField(upload_to='item_pics',blank=False,null=True)
   item_des = models.TextField(blank=True,null=True)
   item_author = models.CharField(max_length=50,blank=False,null=True)
   item_name = models.CharField(max_length=50,blank=False,null=True)
   item_type = models.CharField(choices=item_choice,blank=False,max_length=50,null=True)
   post_datetime = models.DateTimeField(default=datetime.datetime.now(),null=True)

homepage/forms.py
from django import forms
from homepage.models import itemInfo
from django.contrib.auth.models import User


class ItemForm(forms.ModelForm):
    class Meta():
        model = itemInfo
        fields = ('item_name','item_type','item_author','item_des','item_pic1','item_pic2')

        

homepage/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest
from django.urls import reverse
from . import forms
from . import models
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import ItemForm
from .models import itemInfo
from loginapp.models import UserProfileInfo
from django.db.models import Q, Count
from django.shortcuts import render, get_object_or_404
from rest_framework import generics
from rest_framework.response import Response
from django.http import JsonResponse
import copy
import json
from django.forms.models import model_to_dict
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt

## other views functions are here.... ##

def home(request):
    psts=itemInfo.objects.values()
    posts = filter(request)
    form = forms.ItemForm()
    piclink = UserProfileInfo.objects.filter(user=request.user).values('profile_picture')
    print("piclink is ",piclink[0]['profile_picture'])
    piclink=piclink[0]['profile_picture']
    context={'form':form,'posts':posts,'piclink':piclink}


    if request.method == 'POST' and request.is_ajax():
        ID = request.POST.get('id')
        p = itemInfo.objects.get(pk=ID) 
        e = User.objects.filter(username=str(p.user)).values('email')
        name = p.item_name 
        usr = str(p.user)
        em=str(e[0]['email'])
        t = p.item_type
        if t=='B':
            t='Book'
        elif t=='S':
            t='Stationary'
        else:
            t='Others'
        dt = p.post_datetime
        by = p.item_author
        des = p.item_des
        pic1 = str(p.item_pic1)
        pic2 = str(p.item_pic2)
        return JsonResponse({'p_name':name,'tp':t,'desc':des,'dt':dt,'by':by,'pic1':pic1,'pic2':pic2,'usr':usr,'em':em})
    else:
        return render(request,'homepage/home.html',context)




def is_valid_queryparam(param):
    return param != '' and param is not None

def filter(request):
    #qs = Journal.objects.all()
    all_posts = itemInfo.objects.all()
    #categories = Category.objects.all()
    title_contains_query = request.GET.get('homesearch')
    book=request.GET.get('book')
    stationary=request.GET.get('stationary')
    others=request.GET.get('others')
    byitemname=request.GET.get('byitemname')
    

    if is_valid_queryparam(title_contains_query):
        all_posts = all_posts.filter(item_name__icontains=title_contains_query)

    if book == 'on':
        all_posts = all_posts.filter(item_type__in=('Book'))

    elif stationary == 'on':
        all_posts = all_posts.filter(item_type__in=('Stationary'))
    
    elif others == 'on':
        all_posts = all_posts.filter(item_type__in=('Others'))

    if byitemname == 'on':
        all_posts = all_posts.order_by('item_name')
        
    return all_posts


def profile(request):
    return HttpResponseRedirect(reverse('user_profile:profile'))

def addpost(request):
    
    if request.method == 'POST':
        form = ItemForm(request.POST,request.FILES)

        if form.is_valid():
            f=form.save(commit=False)
            f.user=request.user
            #f.user.set([request.user]
            #form.user = User.objects.get(username=request.user.username)
            
            f.save()

            return HttpResponseRedirect(reverse('homepage:home'))
    
    return HttpResponseRedirect(reverse('homepage:home'))

def addpost1(request):
    
    if request.method == 'POST':
        form = ItemForm(request.POST,request.FILES)

        if form.is_valid():
            f=form.save(commit=False)
            f.user=request.user
            #f.user.set([request.user]
            #form.user = User.objects.get(username=request.user.username)
            
            f.save()

            return HttpResponseRedirect(reverse('homepage:myposts'))
    
    return HttpResponseRedirect(reverse('homepage:myposts'))


def myPosts(request):
    psts=itemInfo.objects.values()
    posts = filter1(request)
    form = forms.ItemForm()
    form1 = forms.ItemForm()
    piclink = UserProfileInfo.objects.filter(user=request.user).values('profile_picture')
    print("piclink is ",piclink[0]['profile_picture'])
    piclink=piclink[0]['profile_picture']
    context={'form':form,'posts':posts,'piclink':piclink,'form1':form1}


    if request.method == 'POST' and request.is_ajax():
        ID = request.POST.get('id')
        p = itemInfo.objects.get(pk=ID) 
        name = p.item_name 
        usr = "dddd"
        t = p.item_type
        if t=='B':
            t='Book'
        elif t=='S':
            t='Stationary'
        else:
            t='Others'
        dt = p.post_datetime
        by = p.item_author
        des = p.item_des
        pic1 = str(p.item_pic1)
        pic2 = str(p.item_pic2)
        return JsonResponse({'p_name':name,'tp':t,'desc':des,'dt':dt,'by':by,'pic1':pic1,'pic2':pic2,'usr':usr})
    else:
        return render(request,'homepage/myposts.html',context)


@csrf_exempt
def deletePost(request):
    if request.method == 'POST' and request.is_ajax():
        ID = request.POST.get('p_id')
        print("ID is ",ID)
        p = itemInfo.objects.get(pk=ID) 
        p.delete()
        return HttpResponseRedirect(reverse('homepage:myposts'))

def filter1(request):
    #qs = Journal.objects.all()
    all_posts = itemInfo.objects.all().filter(user=request.user)
    #categories = Category.objects.all()
    title_contains_query = request.GET.get('homesearch')
    book=request.GET.get('book')
    stationary=request.GET.get('stationary')
    others=request.GET.get('others')
    byitemname=request.GET.get('byitemname')
    

    if is_valid_queryparam(title_contains_query):
        all_posts = all_posts.filter(item_name__icontains=title_contains_query)

    return all_posts

#@csrf_exempt
#def edit_post_data(request):
#    if request.method == 'POST' and request.is_ajax():
#        ID = request.POST.get('p_id')
#        p = itemInfo.objects.get(pk=ID) 
#        name = p.item_name 
#        t = p.item_type
#        dt = p.post_datetime
#        by = p.item_author
#        des = p.item_des
#        pic1 = str(p.item_pic1)
#        pic2 = str(p.item_pic2)
#        return JsonResponse({'p_name':name,'tp':t,'desc':des,'dt':dt,'by':by,'pic1':pic1,'pic2':pic2, 'id':ID}) 
    

def edit_post(request,p):
    pt = itemInfo.objects.get(pk=p)
    form = forms.ItemForm(instance=pt)
    piclink = UserProfileInfo.objects.filter(user=request.user).values('profile_picture')
    print("piclink is ",piclink[0]['profile_picture'])
    piclink=piclink[0]['profile_picture']

    if request.method == "POST":
        form = forms.ItemForm(request.POST,request.FILES,instance=pt)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('homepage:myposts'))
    else:
        return render(request,'homepage/edit_post.html',{'editform':form,'piclink':piclink})
        

templates/homepage/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Book Sharing Portal</title>
    <link rel="stylesheet" href="../../static/homepage/home.css"/>
    <script src="../../static/homepage/home.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  </head>
  
  <body style="padding-top: 60px; ">
    
    <nav class="navbar navbar-expand-sm fixed-top" style="background-color: #285163; ">
      {% block nav_block %}
      {% endblock %}  
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/homepage/edit_post.html
{% extends "homepage/base.html" %}
{% load static %}
{% block nav_block %}

<style>
  .container-4{
  overflow: hidden;
  width: 300px;
  vertical-align: middle;
  white-space: nowrap;
}
.container-4 input#search{
  width: 300px;
  height: 35px;
  background: white;
  border: none;
  font-size: 10pt;
  float: left;
  color: #111;
  padding-left: 15px;
  -webkit-border-radius: 5px;
  -moz-border-radius: 5px;
  border-radius: 5px;
}
.container-4 input#search::-webkit-input-placeholder {
   color: #65737e;
}
 
.container-4 input#search:-moz-placeholder { /* Firefox 18- */
   color: #65737e;  
}
 
.container-4 input#search::-moz-placeholder {  /* Firefox 19+ */
   color: #65737e;  
}
 
.container-4 input#search:-ms-input-placeholder {  
   color: #65737e;  
}
.container-4 button.icon{
  -webkit-border-top-right-radius: 5px;
  -webkit-border-bottom-right-radius: 5px;
  -moz-border-radius-topright: 5px;
  -moz-border-radius-bottomright: 5px;
  border-top-right-radius: 5px;
  border-bottom-right-radius: 5px;
 
  border: none;
  background: lightgrey;
  height: 50px;
  width: 50px;
  color: #4f5b66;
  opacity: 0;
  font-size: 10pt;
 
  -webkit-transition: all .55s ease;
  -moz-transition: all .55s ease;
  -ms-transition: all .55s ease;
  -o-transition: all .55s ease;
  transition: all .55s ease;
}
.container-4:hover button.icon, .container-4:active button.icon, .container-4:focus button.icon{
    outline: none;
    opacity: 1;
    height: 35px;
    margin-left: -50px;
  }
 
  .container-4:hover button.icon:hover{
    background: grey;
  }
</style>
<ul class="navbar-nav mr-auto">
  <li class="nav-item">
    <a class="navbar-brand" style="color: white" href="{% url 'homepage:home' %}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="addp" style="color: white; margin-top: 2px;" href="#" data-toggle="modal" data-target="#myModal">Add Post</a>
  </li>
</ul><!--   #17a2b8;  -->

  <div  method="GET" action="." style="margin-left: 20px; margin-right: 20px;" class="form-inline ml-auto">
    <form class=" my-2 my-lg-0" style="margin-right: -90px;" >
      <div class="box">
        <div class="container-4">
          <input style="width: 200px; height: 35px;" id="search" type="text" placeholder="Search" aria-label="Search" name="homesearch" />
          <button style="height: 35px;" class="icon" type="submit"><i class="fa fa-search"></i></button>
        </div>
      </div>
  
    </form>
  
    
  <li class="nav-item dropdown ml-auto" style="margin-top: -2rem;">
    <a class="nav-link dropdown-toggle mx-3" data-toggle="dropdown" 
    href="#" role="button" aria-haspopup="true" aria-expanded="false">
    <img src="/media/{{piclink}}" 
    class="ml-auto" style="position: absolute; margin-left: 0px; width: 60%; height: 50%; border-radius: 10px;" >
      </a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="{% url 'homepage:myposts' %}">My Post</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'homepage:profile' %}">Profile</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'loginapp:user_logout' %}">Logout</a>
      
    </div>
  </li>
</div>
{% endblock %}
{% block body_block %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{editform.as_p}}
    <input type="submit">
</form>

{% endblock %}

templates/homepage/myposts.html
{% extends "homepage/base.html" %}
{% load static %}
{% block nav_block %}
<style>
   
  .container-4{
  overflow: hidden;
  width: 300px;
  vertical-align: middle;
  white-space: nowrap;
}
.container-4 input#search{
  width: 300px;
  height: 35px;
  background: white;
  border: none;
  font-size: 10pt;
  float: left;
  color: #111;
  padding-left: 15px;
  -webkit-border-radius: 5px;
  -moz-border-radius: 5px;
  border-radius: 5px;
}
.container-4 input#search::-webkit-input-placeholder {
   color: #65737e;
}
 
.container-4 input#search:-moz-placeholder { /* Firefox 18- */
   color: #65737e;  
}
 
.container-4 input#search::-moz-placeholder {  /* Firefox 19+ */
   color: #65737e;  
}
 
.container-4 input#search:-ms-input-placeholder {  
   color: #65737e;  
}
.container-4 button.icon{
  -webkit-border-top-right-radius: 5px;
  -webkit-border-bottom-right-radius: 5px;
  -moz-border-radius-topright: 5px;
  -moz-border-radius-bottomright: 5px;
  border-top-right-radius: 5px;
  border-bottom-right-radius: 5px;
 
  border: none;
  background: lightgrey;
  height: 50px;
  width: 50px;
  color: #4f5b66;
  opacity: 0;
  font-size: 10pt;
 
  -webkit-transition: all .55s ease;
  -moz-transition: all .55s ease;
  -ms-transition: all .55s ease;
  -o-transition: all .55s ease;
  transition: all .55s ease;
}
.container-4:hover button.icon, .container-4:active button.icon, .container-4:focus button.icon{
    outline: none;
    opacity: 1;
    height: 35px;
    margin-left: -50px;
  }
 
  .container-4:hover button.icon:hover{
    background: grey;
  }
</style>
<ul class="navbar-nav mr-auto">
  <li class="nav-item">
    <a class="navbar-brand" style="color: white" href="{% url 'homepage:home' %}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="addp" style="color: white; margin-top: 2px;" href="#" data-toggle="modal" data-target="#myModal">Add Post</a>
  </li>
</ul><!--   #17a2b8;  -->

  <div  method="GET" action="." style="margin-left: 20px; margin-right: 20px;" class="form-inline ml-auto">
    <form class=" my-2 my-lg-0" style="margin-right: -90px;" >
      <div class="box">
        <div class="container-4">
          <input style="width: 200px; height: 35px;" id="search" type="text" placeholder="Search" aria-label="Search" name="homesearch" />
          <button style="height: 35px;" class="icon" type="submit"><i class="fa fa-search"></i></button>
        </div>
      </div>
  
    </form>
  
    
  <li class="nav-item dropdown ml-auto" style="margin-top: -2rem;">
    <a class="nav-link dropdown-toggle mx-3" data-toggle="dropdown" 
    href="#" role="button" aria-haspopup="true" aria-expanded="false">
    <img src="/media/{{piclink}}" 
    class="ml-auto" style="position: absolute; margin-left: 0px; width: 60%; height: 50%; border-radius: 10px;" >
      </a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="{% url 'homepage:myposts' %}">My Post</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'homepage:profile' %}">Profile</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'loginapp:user_logout' %}">Logout</a>
      
    </div>
  </li>
</div>
{% endblock %}

{% block body_block %}


<style>
.navbar-brand:hover{
  color: black;
}

.cards-list {
  z-index: 0;
  width: 100%;
  display: flex;
  justify-content: space-around;
  flex-wrap: wrap;
}

.card {
  float: left; 
  margin-left: 30px;
  margin-top:20px;
  width: 232px;
  height: 260px;
  border-radius: 40px;
  box-shadow: 5px 5px 3px 1px rgba(0,0,0,0.1), -5px -5px 3px 1px rgba(0,0,0,0.22);
  cursor: pointer;
  transition: 0.4s;
}

.card .card_image {
  width: inherit;
  height: inherit;
  border-radius: 40px;
}

.card .card_image img {
  width: inherit;
  height: inherit;
  border-radius: 40px;
  object-fit: cover;
}

.card .card_title {
  text-align: center;
  border-radius: 0px 0px 40px 40px;
  font-family: sans-serif;
  font-weight: bold;
  font-size: 30px;
  margin-top: -10px;
  height: 40px;
}

.card:hover {
  transform: scale(0.9, 0.9);
  box-shadow: 5px 5px 30px 15px rgba(0,0,0,0.25), 
    -5px -5px 30px 15px rgba(0,0,0,0.22);
}

.title-white {
  color: white;
}

.title-black {
  color: black;
}

@media all and (max-width: 500px) {
  .card-list {
    /* On small screens, we are no longer using row direction but column */
    flex-direction: column;
  }
}
.modal-dialog-center {
    margin-top: 10%;
}

</style>

<div class="modal fade" id="myModal">
  <div class="modal-dialog modal-lg ">
    <div class="modal-content">
    
      
      <div class="modal-header" style="background-color: #17a2b8;">
        <center><h4 class="modal-title">Add Post</h4></center>
        <button type="button" class="close" data-dismiss="modal">&times;</button> 
      </div>
      
      
      <div class="modal-body">
        <form method="POST" action="{% url 'homepage:addpost1' %}" enctype="multipart/form-data">
          {% csrf_token %}
          {{form.as_p}}
          
          <input type="submit" value="Submit" >
        </form>
      </div>
      
      <div class="modal-footer" style="background-color: #17a2b8;">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
      
    </div>
  </div>
</div>

</div>


<script>

  
$(function(){
      $('.show_product').on('click', function (e) {
          e.preventDefault();
          let product_id = $(this).attr('id');

          $.ajax({
              url:'/homepage/myposts/',
              type:'POST',
              data: $('#form_have_product_'+product_id).serialize(),
              success:function(response){
                  console.log(response);
                  $('.show_product').trigger("reset");
                  openModal(response);
              },
              error:function(){
                  console.log('something went wrong here');
              },
          });
      });
  });
 
  function openModal(product_data){
    $('#product_name').text(product_data.p_name);
    $('#desc').text(product_data.desc);
    $('#datetime').text(product_data.dt);
    $('#by').text("By "+product_data.by);
    $('#type').text(product_data.tp);
    $('#pic1').attr('src','/media/'+product_data.pic1)
    $('#pic2').attr('src','/media/'+product_data.pic2)
  };

  $(function(){
      $('.delete_post').on('click', function (e) {
        var result = confirm("Do you really want to delete ?");
        if (result) {
          e.preventDefault();
          let post_id = $(this).attr('id');
          $.ajax({
              url:'/homepage/delete/',
              type:'POST',
              data: {'p_id':post_id},
              success:function(response){
                  console.log(response);
                  location.reload();
              },
              error:function(){
                  console.log('something went wrong here');
              },
          });
    
        }       
         
      });
  });

  // $(function(){
  //     $('.edit_post').on('click', function (e) {
  //         e.preventDefault();
  //         let product_id = $(this).attr('id');

  //         $.ajax({
  //             url:'/homepage/edit_post_data/',
  //             type:'POST',
  //             data: {'p_id':product_id},
  //             success:function(response){
  //                 console.log(response);
  //                 $('.editform').trigger("reset");
  //                 openModal1(response);
  //             },
  //             error:function(){
  //                 console.log('something went wrong here');
  //             },
  //         });
  //     });
  // });
 
  // function openModal1(product_data){
  //   $('#id_item_name').attr('value',''+product_data.p_name);
  //   $('#id_item_author').attr('value',''+product_data.by);
  //   $('#id_item_des').val(product_data.desc);
  // };




</script>

<div class="modal animated fade" tabindex="-1" id="myModal1">
  <div class="modal-dialog modal-lg modal-dialog-center">
    <div class="modal-content">
      <div class="modal-body" style="height:382px;">
        <div class="row">
          <div class="col-lg-5">
            <div id="carousel-thumb" class="carousel slide carousel-fade carousel-thumbnails" data-ride="carousel">
              <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                  <img id="pic1" style="height: 350px;" class="d-block w-100">
                </div>
                <div class="carousel-item">
                  <img id="pic2" style="height: 350px" class="d-block w-100">
                </div>
              </div>
              <a class="carousel-control-prev" href="#carousel-thumb" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carousel-thumb" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
          <div class="col-lg-6" style="padding-left: 10px; margin-top: 1rem; word-wrap: break-word;">
            <center><h2 id="product_name" style="white-space: initial; overflow-y: auto; height: 50px;"></h2></center>
            <center><p id="type"></p> </center>
            <center><p style="margin-top: -2px;" id="by"></p></center>
            <div id="description1" class="description1" 
            style="color: black; background-color: #fafafa; overflow-y: auto;width: 430px; height: 180px; word-wrap: break-word;" >
                <p id="desc" style="white-space: initial;"></p>
            </div>
            <div style="position: absolute;
            bottom: 5px;
            color: gray;
            right: 5px;
            margin-bottom: -18px; margin-right: -60px; padding-right: 0px;" id="datetime"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

  {% for i in posts%}
  <div class="card 1" >
    <div style="height: 80%; width: 232px;">
    <div class="card_image show_product" data-toggle="modal" 
    data-target="#myModal1" id="{{i.id}}" data-id="{{i.id}}" style="height: 92%;"> <img src="/media/{{i.item_pic1}}" /> </div>
    <div class="card_title title-white show_product" data-toggle="modal" 
    data-target="#myModal1" id="{{i.id}}" data-id="{{i.id}}" style="word-wrap: break-word; height: 7%;">
      <p style="color: black; font-size: 15px;" style="white-space: initial;">{{i.item_name|slice:"0:20"}}</p>
    </div>
    <form name="form" action="#" id="form_have_product_{{i.id}}" method="POST">
      {% csrf_token %}
      <input name="id" id="product_id_submit" type="text" value="{{i.id}}" hidden="true"/>
    </form>
    </div>
    <div style="height: 25%; width: 100%; background-color: lightgrey; border-radius: 10px 10px 30px 30px;">

      <a class="delete_post" id="{{i.id}}" 
      style="height: 100%; width: 50%; float: left; 
      border-radius: 40px;"><center><i class="fa fa-trash" style="font-size: 46px; color:grey; margin-top: 7%;"
       aria-hidden="true"></i></center></a>

      <a id="{{i.id}}" class="edit_post" href="{% url 'homepage:edit_post' i.id %}" 
      style="height: 20%; width: 50%; float: right; border-radius: 40px;"><center>
      <i style="font-size:48px; color:grey; margin-top: 8%;" class="fa fa-edit"></i></center> </a>

    </div>
  </div>  
{% endfor%}
{% endblock %}