BookSharingPortal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from loginapp import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^loginapp/',include('loginapp.urls')),
    url(r'^homepage/',include('homepage.urls')),
    url(r'^user_profile/',include('user_profile.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.conf.urls import url
from homepage import views
from django.conf.urls.static import static
from django.conf import settings
# SET THE NAMESPACE!
app_name = 'homepage'

urlpatterns=[
    url(r'^home/$',views.home,name="home"),
    url(r'^profile/$',views.profile,name="profile"),
    url(r'^addpost/$',views.addpost,name="addpost"),
    url(r'^addpost1/$',views.addpost1,name="addpost1"),
    url(r'^myposts/$',views.myPosts,name="myposts"),
    url(r'^delete/$',views.deletePost,name="delete_post"),
    url(r'^edit_post/(?P<p>.*)/$',views.edit_post,name="edit_post"),
    #url(r'^edit_post_data/$',views.edit_post_data,name="edit_post_data"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginapp/urls.py
from django.conf.urls import url
from loginapp import views
from django.conf.urls.static import static
from django.conf import settings
# SET THE NAMESPACE!
app_name = 'loginapp'

urlpatterns=[
    url(r'^$',views.index,name="index"),
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^user_logout/$',views.user_logout,name='user_logout'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.conf.urls import url
from user_profile import views
from django.urls import path

app_name = 'user_profile'

urlpatterns = [
    url(r'^profile/$',views.user_profile,name="profile"),
    path('edit_profile/',views.edit_profile,name = "edit_profile"),
    path('change_password/',views.change_password,name = "change_password"),
]

user_profile/models.py
from django.db import models

# Create your models here.

user_profile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from loginapp.models import UserProfileInfo

class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name',
        )

class EditProfileInfoForm(UserChangeForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site','phone_number','profile_picture')

user_profile/views.py
from django.shortcuts import render , redirect, reverse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from django.http import HttpResponseRedirect
from user_profile.forms import EditProfileForm,EditProfileInfoForm
from django.contrib.auth import update_session_auth_hash
from loginapp.forms import ExtendedUserCreationForm,UserProfileInfoForm
from loginapp.models import UserProfileInfo


def user_profile(request):
    piclink = UserProfileInfo.objects.filter(user=request.user).values('profile_picture')
    print("piclink is ",piclink[0]['profile_picture'])
    piclink=piclink[0]['profile_picture']
    if request.method == "POST":
        form = UserProfileInfoForm(request.POST,instance=request.user)
        #phone_number = request.POST.get('phone_number')
        print(form.data)
        phone_number = form.data['phone_number']
        args = {'user':request.user,'form':form,'phone_number':phone_number[0],'piclink':piclink}
        return render(request,'user_profile/index.html',args)
    else:

        args = {'user':request.user , 
                'phone_number': request.user.userprofileinfo.phone_number,
                'portfolio_site':request.user.userprofileinfo.portfolio_site,
                'profile_picture':request.user.userprofileinfo.profile_picture,
                'piclink':piclink}
        print('profile_picture : {}'.format(request.user.userprofileinfo.profile_picture))
        return render(request,'user_profile/index.html', args)

def edit_profile(request):
    piclink = UserProfileInfo.objects.filter(user=request.user).values('profile_picture')
    print("piclink is ",piclink[0]['profile_picture'])
    piclink=piclink[0]['profile_picture']
    if request.method == "POST":
        print('In Post')
        #form = EditProfileForm(request.POST, instance = request.user)
        # form1 = EditProfileForm(request.POST, instance = request.user)
        # form2 = EditProfileInfoForm(request.POST, instance = request.user)
        form1 = ExtendedUserCreationForm(request.POST,request.FILES, instance = request.user)
        form2 = UserProfileInfoForm(request.POST,request.FILES,instance=request.user.userprofileinfo)
        if form1.is_valid() and form2.is_valid():
            form1.save()
            form2.save()
            # user = form1.save()
            # profile = form2.save(commit=False)
            # profile.user = user
        #     # return reverse('../templates/user_profile/index.html')
            # return redirect("/templates/user_profile/index.html")
            print('near to context')
            # if 'picture' in request.FILES:
            #     profile.profile_picture = request.FILES['picture']
            #     print('Profile_picture',profile.profile_picture)
            # profile.save()
            args = {'user':request.user , 
                'phone_number': request.user.userprofileinfo.phone_number,
                'portfolio_site':request.user.userprofileinfo.portfolio_site,
                'profile_picture':request.user.userprofileinfo.profile_picture,'piclink':piclink}
            print('phone_number : {}'.format(request.user.userprofileinfo.phone_number))
            print('profile_picture : {}'.format(request.user.userprofileinfo.profile_picture))
            return render(request,'../templates/user_profile/index.html',args)
            #return redirect('/user_profile/profile/')
            #return reverse('index')
    else:
        # form1 = EditProfileForm(instance=request.user)
        # form2 = EditProfileInfoForm(instance=request.user)
        # args = {'form1': form1,'form2':form2}
        print('ELSE Edit profile GET')
        form1 = ExtendedUserCreationForm(instance = request.user)
        form2 = UserProfileInfoForm(instance=request.user.userprofileinfo)
        args = {'form1': form1,'form2':form2,'piclink':piclink}
        return render(request,'../templates/user_profile/edit_profile.html',args)
        

def change_password(request):
    piclink = UserProfileInfo.objects.filter(user=request.user).values('profile_picture')
    print("piclink is ",piclink[0]['profile_picture'])
    piclink=piclink[0]['profile_picture']
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user = request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            args = {'user':request.user , 
                'phone_number': request.user.userprofileinfo.phone_number,
                'portfolio_site':request.user.userprofileinfo.portfolio_site,
                'profile_picture':request.user.userprofileinfo.profile_picture,'piclink':piclink}
            print('phone_number : {}'.format(request.user.userprofileinfo.phone_number))
            return render(request,'../templates/user_profile/index.html',args)
            #return redirect('index')
        else:
            print('>>>>>> nahi hua ')
            return render(request,'../templates/user_profile/change_password.html')
            #return redirect('change_password')
    else:
        form = PasswordChangeForm(user=request.user)
        print('>>> Else hua GET')

        args = {'form': form,'piclink':piclink}
        return render(request,'../templates/user_profile/change_password.html',args)

templates/user_profile/change_password.html
{% block body %}

<div class="container">

<form method = "POST">
{% csrf_token %}
{{ form.as_p }}
<button type = "submit" name = "button" value = "submit"> Submit </button>

</form>

</div>

{% endblock  %}

templates/user_profile/edit_profile.html
{% block body %}

<div class="container">

<form method = "POST" enctype="multipart/form-data">
{% csrf_token %}
{% comment %} {{ form1.as_p }}
{{ form2.as_p }} {% endcomment %}
{{ form1.as_p }}
{{ form2.as_p}}
<button type = "submit" value = "submit"> Submit </button>

</form>

</div>

{% endblock  %}

templates/user_profile/index.html

<!DOCTYPE html>

<html lang="en">
<head>
	<title>User Profile</title>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
	<link href="../../static/user_profile/img/favicon.ico" rel="shortcut icon"/>
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,400i,600,600i,700" rel="stylesheet">
	<link rel="stylesheet" href="../../static/user_profile/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="../../static/user_profile/css/font-awesome.min.css"/>
	<link rel="stylesheet" href="../../static/user_profile/css/flaticon.css"/>
	<link rel="stylesheet" href="../../static/user_profile/css/owl.carousel.css"/>
	<link rel="stylesheet" href="../../static/user_profile/css/magnific-popup.css"/>
	<link rel="stylesheet" href="../../static/user_profile/css/style.css"/>

</head>
<body>
	

	<nav class="navbar navbar-expand-sm fixed-top" style="background-color: #285163;">
	<ul class="navbar-nav mr-auto">
		<li class="nav-item">
		  <a class="navbar-brand" style="color: white" href="{% url 'homepage:home' %}">Home</a>
		</li>
		<li class="nav-item">
		  <a class="nav-link" id="addp" style="color: white; margin-top: 2px;" href="{% url 'user_profile:edit_profile' %}">Edit profile</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" id="addp" style="color: white; margin-top: 2px;" href="{% url 'user_profile:change_password' %}">Change Password</a>
		  </li>
	  </ul><!--   #17a2b8;  -->
	  
		
		  
		<li class="nav-item dropdown ml-auto" style="margin-top: -2rem;">
		  <a class="nav-link dropdown-toggle mx-3" data-toggle="dropdown" 
		  href="#" role="button" aria-haspopup="true" aria-expanded="false">
		  <img src="/media/{{piclink}}" 
		  class="ml-auto" style="position: absolute; margin-left: 0px; width: 60%; height: 50%; border-radius: 10px;" >
			</a>
		  <div class="dropdown-menu">
			<a class="dropdown-item" href="{% url 'homepage:myposts' %}">My Post</a>
			<div class="dropdown-divider"></div>
			<a class="dropdown-item" href="{% url 'loginapp:user_logout' %}">Logout</a>
			
		  </div>
		</li>
	 
	  </nav>
	<div id="preloder">
		<div class="loader"></div>
	</div>


    <section class="hero-section spad">
		<div class="container-fluid">
			<div class="row">
				<div class="col-xl-10 offset-xl-1">
					<div class="row">
						<div class="col-lg-6">
							<div class="hero-text">
								<h2 style="font-size:90px; ">{{ user }}</h2>
								</div>
							<div class="hero-info" style="width: 100%;">
								<h2>General Info</h2>
								<ul>
									<li><span>First Name</span>{{ user.first_name }}</li>
									<li><span>Last Name</span>{{ user.last_name }}</li>
									<li><span>E-mail</span>{{ user.email }}</li>

									<li><span>Phone </span>{{ phone_number }}</li>
									<li><span>Portfolio site </span>{{ portfolio_site }}</li>
								</ul>
							</div>
						</div>
						<div class="col-lg-6">
							<figure class="hero-image">
								<img style="border-radius: 50%; 
								width:400px;height:400px; margin-left: 120px;" src="../../media/{{ profile_picture }}" alt="5">
							</figure>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<script src="../../static/user_profile/js/jquery-2.1.4.min.js"></script>
	<script src="../../static/user_profile/js/bootstrap.min.js"></script>
	<script src="../../static/user_profile/js/owl.carousel.min.js"></script>
	<script src="../../static/user_profile/js/magnific-popup.min.js"></script>
	<script src="../../static/user_profile/js/circle-progress.min.js"></script>
	<script src="../../static/user_profile/js/main.js"></script>
</body>
</html>