BookSharingPortal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from loginapp import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^loginapp/',include('loginapp.urls')),
    url(r'^homepage/',include('homepage.urls')),
    url(r'^user_profile/',include('user_profile.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.conf.urls import url
from homepage import views
from django.conf.urls.static import static
from django.conf import settings
# SET THE NAMESPACE!
app_name = 'homepage'

urlpatterns=[
    url(r'^home/$',views.home,name="home"),
    url(r'^profile/$',views.profile,name="profile"),
    url(r'^addpost/$',views.addpost,name="addpost"),
    url(r'^addpost1/$',views.addpost1,name="addpost1"),
    url(r'^myposts/$',views.myPosts,name="myposts"),
    url(r'^delete/$',views.deletePost,name="delete_post"),
    url(r'^edit_post/(?P<p>.*)/$',views.edit_post,name="edit_post"),
    #url(r'^edit_post_data/$',views.edit_post_data,name="edit_post_data"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginapp/urls.py
from django.conf.urls import url
from loginapp import views
from django.conf.urls.static import static
from django.conf import settings
# SET THE NAMESPACE!
app_name = 'loginapp'

urlpatterns=[
    url(r'^$',views.index,name="index"),
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^user_logout/$',views.user_logout,name='user_logout'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from django.core.validators import RegexValidator


class UserProfileInfo(models.Model):
    
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField()
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17) 
    profile_picture = models.ImageField(upload_to = 'profile_pics')
   
    def __str__(self):
        return self.user.username

loginapp/forms.py
from django import forms
from django.forms import ModelForm
from loginapp.models import UserProfileInfo
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class ExtendedUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

    class Meta:
        model = User
        fields = ('username','email','first_name','last_name')
    def save(self,commit=True):
        user =super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site','phone_number','profile_picture')

loginapp/views.py
from django.shortcuts import render
from loginapp.forms import ExtendedUserCreationForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from django.shortcuts import render
from django.contrib.auth.decorators import login_required




def register(request):
    template = 'loginapp/registration.html'
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ExtendedUserCreationForm(request.POST,request.FILES)
        profile_form = UserProfileInfoForm(request.POST,request.FILES)

        if form.is_valid() and profile_form.is_valid():
            
            user = form.save()
            profile = profile_form.save(commit=False)

            profile.user = user
            user.set_password(user.password)
            profile.save()

               
            return HttpResponseRedirect(reverse('loginapp:user_login'))

   
    else:
        form = ExtendedUserCreationForm()
        profile_form = UserProfileInfoForm()

    return render(request, template,{'form':form,
                           'profile_form':profile_form})










def index(request):
    return render(request,'loginapp/index.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('homepage:home'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'loginapp/login.html', {})

templates/loginapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Book Sharing Portal</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        {% block nav_block%}
        {% endblock %}  
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/loginapp/index.html
{% comment %} {% extends "loginapp/base.html" %} {% endcomment %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="../../static/loginapp/fonts/material-icon/css/material-design-iconic-font.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="../../static/loginapp/css/style.css">

</head>
<body>
{% block nav_block %}

<!--<ul class="nav navbar-nav">
  <li><a class="navbar-link" href="{% url 'loginapp:register' %}">Register</a></li>  
  <li><a class="navbar-link" href="{% url 'loginapp:user_login' %}">Login</a></li>
</ul>-->
{% endblock %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1 style="text-align: center;">Welcome to Book Sharing Portal</h1>
    <!--<h2>Register or Login if you'd like to use book sharing portal</h2>-->
  </div>
</div>
  <!--<div class="main">-->

        <!-- Sign up form -->
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Sign In <br> OR <br>Sign Up </h2>
                        <form method="POST" action = "{% url 'loginapp:register' %}" class="register-form" id="register-form" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group form-button">
                                
                                <input type="submit" name="signup" id="signup" class="form-submit" style = "font-size: 20px;" value="Register"/>
                            </div>
                        </form>
                        <!--<form method="POST" action = "{% url 'loginapp:user_login' %}" class="register-form" id="register-form" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group form-button">
                                
                                <input type="submit" name="signin" id="signup" class="form-submit" value="Sign In"/>
                            </div>
                        </form>-->
                    </div>
                    <div class="signup-image">
                        <figure><img src="../../static/loginapp/images/signup-image.jpg" alt="sing up image"></figure>
                        <a href="{% url 'loginapp:user_login' %}" style = "font-size: 20px;" class="signup-image-link">I am already a member</a>
                    </div>
                </div>
            </div>
        </section>
    <!--</div>-->

    <!-- JS -->
    <script src="../../static/loginapp/vendor/jquery/jquery.min.js"></script>
    <script src="../../static/loginapp/js/main.js"></script>
  {% endblock %}
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

templates/loginapp/login.html
{% comment %} {% extends 'loginapp/base.html' %} {% endcomment %}
{% comment %} {% block body_block %} {% endcomment %}
<!--  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'loginapp:user_login' %}">
          {% csrf_token %}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>-->
{% comment %} {% endblock %} {% endcomment %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign In</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="../../static/loginapp/fonts/material-icon/css/material-design-iconic-font.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="../../static/loginapp/css/style.css">

</head>
<body>

{% block body_block %}
     <!--<div class="main"> -->
        <!-- Sing in  Form -->
        <section class="sign-in">
            <div class="container">
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src="../../static/loginapp/images/signin-image.jpg" alt="sing up image"></figure>
                        <a href="{% url 'loginapp:register' %}" style="font-size:20px;" class="signup-image-link">Create an account</a>
                    </div>

                    <div class="signin-form">
                        <h2 class="form-title">Sign In</h2>
                        <form method="POST" action="{% url 'loginapp:user_login' %}" class="register-form" id="login-form">
                            {%csrf_token%}
                            <div class="form-group">
                                <label for="username"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="username" id="your_name" placeholder="Username"/>
                            </div>
                            <div class="form-group">
                                <label for="password"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="password" id="your_pass" placeholder="Password"/>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signin" id="signin" class="form-submit" value="Login"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>

    <!-- </div>-->
    {% endblock %}
    <!-- JS -->
    <script src="../../static/loginapp/vendor/jquery/jquery.min.js"></script>
    <script src="../../static/loginapp/js/main.js"></script>
   
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

templates/loginapp/registration.html
{% extends "loginapp/base.html" %}
{% load static %}
{% block body_block %}
<!--<div class="container">
    <form method="POST" action="{% url 'loginapp:register' %}" >
      {% csrf_token %}
      <div class="col-md-8 col-md-offset-2">
          <div class="panel panel-default">
              <div class="panel-heading">Register</div>
              <div class="panel-body">
                  {% if error_message %}
                      <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                  {% endif %}
                  
                  <div class="form-group clearfix">
                      <label class="col-md-4 control-label text-right">Username<span class="text-red">*</span>:</label>
                      <div class="col-md-6">
                          {{ form.username }}
                      </div>
                  </div>
                  <div class="form-group clearfix">
                      <label class="col-md-4 control-label text-right">Email<span class="text-red">*</span>:</label>
                      <div class="col-md-6">
                          {{ form.email }}
                      </div>
                  </div>
                  <div class="form-group clearfix">
                      <label class="col-md-4 control-label text-right">Password<span class="text-red">*</span>:</label>
                      <div class="col-md-6">
                          {{ form.password}}
                      </div>
                  </div>
                  <div class="form-group clearfix">
                    <label class="col-md-4 control-label text-right">Password2<span class="text-red">*</span>:</label>
                    <div class="col-md-6">
                        {{ form.password2 }}
                    </div>
                </div>
                  <div class="form-group clearfix">
                      <label class="col-md-4 control-label text-right">First Name:</label>
                      <div class="col-md-6">
                          {{ form.first_name }}
                      </div>
                  </div>
                  <div class="form-group clearfix">
                      <label class="col-md-4 control-label text-right">Last Name:</label>
                      <div class="col-md-6">
                          {{ form.last_name }}
                      </div>
                  </div>
                  <div class="form-group clearfix">
                      <label class="col-md-4 control-label text-right">Phone Number:</label>
                      <div class="col-md-6">
                          {{ profile_form.phone_number }}
                      </div>
                  </div>
                  <div class="form-group clearfix">
                    <label class="col-md-4 control-label text-right">portfolio site:</label>
                    <div class="col-md-6">
                        {{ profile_form.portfolio_site }}
                    </div>
                </div>
                  <div class="col-md-6 col-md-offset-4">
                      <input type="submit" value="Register" class="btn btn-success">
                  </div>
              </div>
          </div>
      </div>
  </form>  -->

<form method="POST" action="{% url 'loginapp:register' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="crate new account">
</form>

</div>
{% endblock %}